CREATE TABLE Moradores
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) DEFAULT NEWID(),
	Telefone BIGINT DEFAULT(FLOOR(RAND()*(100000000-50000000+1)+50000000)),
	UF CHAR(2) DEFAULT('SP')
)
GO

CREATE INDEX IDX_Nome ON Moradores(UF)
GO

INSERT INTO Moradores DEFAULT VALUES
GO 10000

SET STATISTICS IO ON;  
SELECT	Id,
		Nome,
		Telefone
	FROM Moradores --WITH(INDEX(IDX_Nome))
	WHERE UF = 'SP'

CREATE INDEX IDX_Nome ON Moradores(UF) INCLUDE(Id, Nome, Telefone) WITH(DROP_EXISTING = ON)
GO